# Generated by Django 4.2.16 on 2024-09-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('is_occupied', models.BooleanField(default=False)),
                ('time_occupied', models.DateTimeField(null=True)),
            ],
        ),
    ]
