# Generated by Django 5.1.1 on 2024-09-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
