# Generated by Django 4.2.16 on 2024-09-13 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_courts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courts',
        ),
    ]
