# Generated by Django 5.1.1 on 2024-09-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_court_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
