# Generated by Django 5.1.1 on 2024-09-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_court_created_alter_court_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Court',
        ),
    ]
